apiVersion: v1
kind: Service
metadata:
  name: flask-restaurant-builder
  labels:
    app: flask-restaurant-builder
spec:
  selector:
    app: flask-restaurant-builder
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      